namespace iE.Core.Reports.Templates;

public static class InspectionComponentCatalog
{
    public static IReadOnlyList<InspectionComponentDefinition> Api510ExternalComponentDefinitions { get; } =
    [
        new()
        {
            ComponentKey = "shell",
            Label = "Shell",
            Standard = "API 510",
            InspectionScope = "External",
            EquipmentFamily = "Pressure Equipment",
            EquipmentSubtype = "Shell and Tube Exchanger",
            RequirementLevel = "minimum",
            DefaultSelected = true,
            FieldTagPrefix = "api510.external.exchanger.shell-tube.shell",
            PressureBoundarySide = "shell-side",
            DesignPressureFieldTag = "api510.external.exchanger.shell-tube.shell-side.design-pressure",
            DesignTemperatureFieldTag = "api510.external.exchanger.shell-tube.shell-side.design-temperature",
            SupportsTminCalculation = true,
            TminCalculationMethod = "UG-27 cylindrical shell",
            SupportsFinding = true,
            SupportsRecommendation = true,
            SupportsRepairRequired = true,
            SupportsPhotoTag = true,
            SupportsSummary = true,
            SupportsNdeRequest = true
        },
        new()
        {
            ComponentKey = "shell-cover",
            Label = "Shell Cover",
            Standard = "API 510",
            InspectionScope = "External",
            EquipmentFamily = "Pressure Equipment",
            EquipmentSubtype = "Shell and Tube Exchanger",
            RequirementLevel = "optional",
            DefaultSelected = false,
            FieldTagPrefix = "api510.external.exchanger.shell-tube.shell-cover",
            PressureBoundarySide = "shell-side",
            DesignPressureFieldTag = "api510.external.exchanger.shell-tube.shell-side.design-pressure",
            DesignTemperatureFieldTag = "api510.external.exchanger.shell-tube.shell-side.design-temperature",
            SupportsTminCalculation = true,
            TminCalculationMethod = "UG-32 formed head",
            SupportsFinding = true, SupportsRecommendation = true, SupportsRepairRequired = true, SupportsPhotoTag = true, SupportsSummary = true, SupportsNdeRequest = true
        },
        new()
        {
            ComponentKey = "channel-channel-head",
            Label = "Channel / Channel Head",
            Standard = "API 510",
            InspectionScope = "External",
            EquipmentFamily = "Pressure Equipment",
            EquipmentSubtype = "Shell and Tube Exchanger",
            RequirementLevel = "minimum",
            DefaultSelected = true,
            FieldTagPrefix = "api510.external.exchanger.shell-tube.channel-channel-head",
            PressureBoundarySide = "tube-side",
            DesignPressureFieldTag = "api510.external.exchanger.shell-tube.tube-side.design-pressure",
            DesignTemperatureFieldTag = "api510.external.exchanger.shell-tube.tube-side.design-temperature",
            SupportsTminCalculation = true,
            TminCalculationMethod = "UG-32 formed head",
            ReviewNotes = "Tube-side design conditions apply.",
            SupportsFinding = true, SupportsRecommendation = true, SupportsRepairRequired = true, SupportsPhotoTag = true, SupportsSummary = true, SupportsNdeRequest = true
        },
        new()
        {
            ComponentKey = "channel-cover",
            Label = "Channel Cover",
            Standard = "API 510",
            InspectionScope = "External",
            EquipmentFamily = "Pressure Equipment",
            EquipmentSubtype = "Shell and Tube Exchanger",
            RequirementLevel = "optional",
            DefaultSelected = false,
            FieldTagPrefix = "api510.external.exchanger.shell-tube.channel-cover",
            PressureBoundarySide = "tube-side",
            DesignPressureFieldTag = "api510.external.exchanger.shell-tube.tube-side.design-pressure",
            DesignTemperatureFieldTag = "api510.external.exchanger.shell-tube.tube-side.design-temperature",
            SupportsTminCalculation = true,
            TminCalculationMethod = "flat cover / channel cover method placeholder",
            SupportsFinding = true,
            SupportsRecommendation = true,
            SupportsRepairRequired = true,
            SupportsPhotoTag = true,
            SupportsSummary = true,
            SupportsNdeRequest = true
        },
        new()
        {
            ComponentKey = "channel-head-dollar-plate",
            Label = "Channel Head / Dollar Plate",
            Standard = "API 510",
            InspectionScope = "External",
            EquipmentFamily = "Pressure Equipment",
            EquipmentSubtype = "Shell and Tube Exchanger",
            RequirementLevel = "optional",
            DefaultSelected = false,
            FieldTagPrefix = "api510.external.exchanger.shell-tube.channel-head-dollar-plate",
            PressureBoundarySide = "tube-side",
            DesignPressureFieldTag = "api510.external.exchanger.shell-tube.tube-side.design-pressure",
            DesignTemperatureFieldTag = "api510.external.exchanger.shell-tube.tube-side.design-temperature",
            SupportsTminCalculation = true,
            TminCalculationMethod = "flat cover / channel cover method placeholder",
            SupportsFinding = true,
            SupportsRecommendation = true,
            SupportsRepairRequired = true,
            SupportsPhotoTag = true,
            SupportsSummary = true,
            SupportsNdeRequest = true
        },
        new()
        {
            ComponentKey = "bonnet-head",
            Label = "Bonnet Head",
            Standard = "API 510",
            InspectionScope = "External",
            EquipmentFamily = "Pressure Equipment",
            EquipmentSubtype = "Shell and Tube Exchanger",
            RequirementLevel = "optional",
            DefaultSelected = false,
            FieldTagPrefix = "api510.external.exchanger.shell-tube.bonnet-head",
            PressureBoundarySide = "tube-side",
            DesignPressureFieldTag = "api510.external.exchanger.shell-tube.tube-side.design-pressure",
            DesignTemperatureFieldTag = "api510.external.exchanger.shell-tube.tube-side.design-temperature",
            SupportsTminCalculation = true,
            TminCalculationMethod = "UG-32 formed head",
            SupportsFinding = true,
            SupportsRecommendation = true,
            SupportsRepairRequired = true,
            SupportsPhotoTag = true,
            SupportsSummary = true,
            SupportsNdeRequest = true
        },
        new()
        {
            ComponentKey = "tubesheet-area",
            Label = "Tubesheet Area",
            Standard = "API 510",
            InspectionScope = "External",
            EquipmentFamily = "Pressure Equipment",
            EquipmentSubtype = "Shell and Tube Exchanger",
            RequirementLevel = "optional",
            DefaultSelected = false,
            FieldTagPrefix = "api510.external.exchanger.shell-tube.tubesheet-area",
            PressureBoundarySide = "shared",
            SupportsTminCalculation = false,
            TminCalculationMethod = "review only unless calculation method is selected",
            ReviewNotes = "Shared/interface region; review only unless a specific calculation method is selected.",
            SupportsFinding = true,
            SupportsRecommendation = true,
            SupportsRepairRequired = true,
            SupportsPhotoTag = true,
            SupportsSummary = true,
            SupportsNdeRequest = true
        },
        new()
        {
            ComponentKey = "nozzles",
            Label = "Nozzles",
            Standard = "API 510",
            InspectionScope = "External",
            EquipmentFamily = "Pressure Equipment",
            EquipmentSubtype = "Shell and Tube Exchanger",
            RequirementLevel = "minimum",
            DefaultSelected = true,
            FieldTagPrefix = "api510.external.exchanger.shell-tube.nozzles",
            ParentComponentRequired = true,
            AllowedParentComponentKeys = ["shell", "channel-channel-head", "shell-cover", "channel-cover", "bonnet-head", "tubesheet-area", "other-component"],
            PressureBoundarySide = "shared",
            DesignPressureFieldTag = "api510.external.exchanger.shell-tube.shell-side.design-pressure",
            DesignTemperatureFieldTag = "api510.external.exchanger.shell-tube.shell-side.design-temperature",
            DesignPressureFieldTagsByPressureBoundarySide = new Dictionary<string, string>
            {
                ["shell-side"] = "api510.external.exchanger.shell-tube.shell-side.design-pressure",
                ["tube-side"] = "api510.external.exchanger.shell-tube.tube-side.design-pressure"
            },
            DesignTemperatureFieldTagsByPressureBoundarySide = new Dictionary<string, string>
            {
                ["shell-side"] = "api510.external.exchanger.shell-tube.shell-side.design-temperature",
                ["tube-side"] = "api510.external.exchanger.shell-tube.tube-side.design-temperature"
            },
            DesignConditionSourceOptions = ["shell-side", "tube-side"],
            ParentThicknessSourceOptions = ["selected-parent", "manual-entry"],
            NozzleLocationRequired = true,
            NozzleLocationOptions = ["shell", "channel-channel-head", "bonnet-head", "tubesheet-area"],
            SupportsTminCalculation = true,
            TminCalculationMethod = "UG-45 nozzle neck minimum thickness",
            SupportsNozzleUg45 = true,
            ReviewNotes = "Nozzle can be assigned to shell-side/tube-side parent. Channel / Channel Head is treated as tube-side for design pressure and temperature. UG-45 metadata required.",
            SupportsFinding = true,
            SupportsRecommendation = true,
            SupportsRepairRequired = true,
            SupportsPhotoTag = true,
            SupportsSummary = true,
            SupportsNdeRequest = true
        },
        new()
        {
            ComponentKey = "nozzles",
            Label = "Nozzles",
            Standard = "API 510",
            InspectionScope = "External",
            EquipmentFamily = "Pressure Equipment",
            EquipmentSubtype = "Horizontal Drum",
            RequirementLevel = "minimum",
            DefaultSelected = true,
            FieldTagPrefix = "api510.external.drum-vessel.horizontal-drum.nozzles",
            ParentComponentRequired = true,
            AllowedParentComponentKeys = ["shell", "heads"],
            NozzleLocationRequired = true,
            NozzleLocationOptions = ["shell", "heads"],
            DesignConditionSourceOptions = ["vessel-side"],
            DesignPressureFieldTag = "api510.external.drum-vessel.design-pressure",
            DesignTemperatureFieldTag = "api510.external.drum-vessel.design-temperature",
            SupportsFinding = true,
            SupportsRecommendation = true,
            SupportsRepairRequired = true,
            SupportsPhotoTag = true,
            SupportsSummary = true,
            SupportsNdeRequest = true
        },
        new()
        {
            ComponentKey = "nozzles",
            Label = "Nozzles",
            Standard = "API 510",
            InspectionScope = "External",
            EquipmentFamily = "Pressure Equipment",
            EquipmentSubtype = "Distillation Tower",
            RequirementLevel = "minimum",
            DefaultSelected = true,
            FieldTagPrefix = "api510.external.tower-column.distillation.nozzles",
            ParentComponentRequired = true,
            AllowedParentComponentKeys = ["shell-courses", "heads"],
            NozzleLocationRequired = true,
            NozzleLocationOptions = ["shell-courses", "heads"],
            DesignConditionSourceOptions = ["tower-side"],
            DesignPressureFieldTag = "api510.external.tower-column.design-pressure",
            DesignTemperatureFieldTag = "api510.external.tower-column.design-temperature",
            SupportsFinding = true,
            SupportsRecommendation = true,
            SupportsRepairRequired = true,
            SupportsPhotoTag = true,
            SupportsSummary = true,
            SupportsNdeRequest = true
        },
        new()
        {
            ComponentKey = "nozzles",
            Label = "Nozzles",
            Standard = "API 510",
            InspectionScope = "External",
            EquipmentFamily = "Pressure Equipment",
            EquipmentSubtype = "Air Cooler / Fin Fan",
            RequirementLevel = "minimum",
            DefaultSelected = true,
            FieldTagPrefix = "api510.external.exchanger.air-cooler.nozzles",
            ParentComponentRequired = true,
            AllowedParentComponentKeys = ["header-box"],
            NozzleLocationRequired = true,
            NozzleLocationOptions = ["header-box"],
            DesignConditionSourceOptions = ["tube-side", "header-box"],
            SupportsFinding = true,
            SupportsRecommendation = true,
            SupportsRepairRequired = true,
            SupportsPhotoTag = true,
            SupportsSummary = true,
            SupportsNdeRequest = true
        },
        new()
        {
            ComponentKey = "nozzles",
            Label = "Nozzles",
            Standard = "API 510",
            InspectionScope = "External",
            EquipmentFamily = "Pressure Equipment",
            EquipmentSubtype = "Double Pipe Exchanger",
            RequirementLevel = "minimum",
            DefaultSelected = true,
            FieldTagPrefix = "api510.external.exchanger.double-pipe.nozzles",
            ParentComponentRequired = true,
            AllowedParentComponentKeys = ["inner-pipe-external", "outer-pipe", "return-bends"],
            NozzleLocationRequired = true,
            NozzleLocationOptions = ["inner-pipe-external", "outer-pipe", "return-bends"],
            DesignConditionSourceOptions = ["inner-pipe-side", "annulus-side"],
            SupportsFinding = true,
            SupportsRecommendation = true,
            SupportsRepairRequired = true,
            SupportsPhotoTag = true,
            SupportsSummary = true,
            SupportsNdeRequest = true
        }
    ];
}
