export type AppRouteDefinition = {
  path: string;
  title: string;
  description: string;
};

export const appPlaceholderRoutes: AppRouteDefinition[] = [
  { path: '/nde-requests', title: 'NDE Requests', description: 'Coming soon: NDE request queue and workflows.' },
  { path: '/reports', title: 'Reports', description: 'Coming soon: role-filtered report views and actions.' },
  { path: '/users-access', title: 'Admin', description: 'Coming soon: user and access administration.' },
  { path: '/downloads', title: 'Downloads', description: 'Coming soon: downloadable files and generated documents.' },
  { path: '/assets', title: 'Assets', description: 'Coming soon: asset registry and lifecycle views.' },
  { path: '/help', title: 'Help', description: 'Coming soon: help resources and support guidance.' },
  { path: '/approval-queue', title: 'Approval Queue', description: 'Coming soon: approval workflows and review queue.' },
  { path: '/nde-reports', title: 'NDE Reports', description: 'Coming soon: NDE report review and tracking.' },
  { path: '/exports', title: 'Exports', description: 'Coming soon: export generation and delivery tools.' },
  { path: '/api-inspection-log', title: 'API Inspection Log', description: 'Coming soon: inspection log views and filtering.' },
  { path: '/my-reports', title: 'My Reports', description: 'Coming soon: personalized report workspace.' },
  { path: '/returned-reports', title: 'Returned Reports', description: 'Coming soon: returned report triage and updates.' },
  { path: '/schedule', title: 'Schedule', description: 'Coming soon: scheduling and assignment planning.' },
  { path: '/results-received', title: 'Results Received', description: 'Coming soon: received results review and routing.' },
  { path: '/overdue', title: 'Overdue', description: 'Coming soon: overdue work and escalation tracking.' },
  { path: '/cancelled', title: 'Cancelled', description: 'Coming soon: cancelled work history and context.' },
  { path: '/facilities', title: 'Facilities', description: 'Coming soon: facility configuration and management.' },
  { path: '/custom-nde-types', title: 'Custom NDE Types', description: 'Coming soon: custom NDE type administration.' },
  { path: '/audit-log', title: 'Audit Log', description: 'Coming soon: audit trail exploration and search.' },
  { path: '/settings', title: 'Settings', description: 'Coming soon: system and user preference controls.' },
  { path: '/system-readiness', title: 'System Readiness', description: 'Coming soon: readiness checks and status dashboards.' },
  { path: '/stress-test-setup', title: 'Stress Test Setup', description: 'Coming soon: stress test setup and execution controls.' },
  { path: '/tenants', title: 'Tenants', description: 'Coming soon: tenant administration and provisioning.' },
];

export const explicitAppRoutes: string[] = [
  '/dashboard',
  '/reports-test',
  '/reports-test/:id',
  '/reports/api-570-piping-external',
  '/calculators/corrosion-rate',
  '/calculators/pipe-lookup',
  '/calculators/pressure-vessels',
  '/nde-requests',
  '/reports',
  '/users-access',
  '/downloads',
  '/assets',
  '/help',
  '/approval-queue',
  '/nde-reports',
  '/exports',
  '/api-inspection-log',
  '/my-reports',
  '/returned-reports',
  '/schedule',
  '/results-received',
  '/overdue',
  '/cancelled',
  '/facilities',
  '/custom-nde-types',
  '/audit-log',
  '/settings',
  '/system-readiness',
  '/stress-test-setup',
  '/tenants',
];
