// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using iE.Core.Reports;

#nullable disable

namespace iE.Core.Reports.Migrations
{
    [DbContext(typeof(InspectionReportsDbContext))]
    [Migration("20260501090000_AddReportReviewHistory")]
    partial class AddReportReviewHistory : Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("iE.Core.Reports.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EquipmentTag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ProcessUnitId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("ProcessUnitId");

                    b.ToTable("Assets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "asset-demo-piping-system",
                            EquipmentTag = "EDR-010-H21",
                            EquipmentType = "Piping",
                            FacilityId = "facility-demo-gulf-coast",
                            IsActive = true,
                            ProcessUnitId = "unit-demo-crude",
                            Service = "Demo Service"
                        });
                });

            modelBuilder.Entity("iE.Core.Reports.ClientOrganization", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("ClientOrganizations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "client-demo-refining",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Demo Refining Client"
                        });
                });

            modelBuilder.Entity("iE.Core.Reports.Facility", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ClientOrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrganizationId");

                    b.ToTable("Facilities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "facility-demo-gulf-coast",
                            ClientOrganizationId = "client-demo-refining",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Demo Gulf Coast Refinery"
                        });
                });

            modelBuilder.Entity("iE.Core.Reports.InspectionReport", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AssetId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CircuitId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ClientOrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EquipmentTag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProcessUnitId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReportNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ClientOrganizationId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("ProcessUnitId");

                    b.HasIndex("Status");

                    b.HasIndex("TemplateId");

                    b.ToTable("InspectionReports", (string)null);
                });

            modelBuilder.Entity("iE.Core.Reports.ProcessUnit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("ProcessUnits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "unit-demo-crude",
                            FacilityId = "facility-demo-gulf-coast",
                            IsActive = true,
                            Name = "Crude Unit",
                            UnitCode = "001"
                        });
                });

            modelBuilder.Entity("iE.Core.Reports.UserFacilityAccess", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ClientOrganizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FacilityId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrganizationId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFacilityAccesses", (string)null);
                });

            modelBuilder.Entity("iE.Core.Reports.Asset", b =>
                {
                    b.HasOne("iE.Core.Reports.Facility", "Facility")
                        .WithMany("Assets")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iE.Core.Reports.ProcessUnit", "ProcessUnit")
                        .WithMany("Assets")
                        .HasForeignKey("ProcessUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Facility");

                    b.Navigation("ProcessUnit");
                });

            modelBuilder.Entity("iE.Core.Reports.Facility", b =>
                {
                    b.HasOne("iE.Core.Reports.ClientOrganization", "ClientOrganization")
                        .WithMany("Facilities")
                        .HasForeignKey("ClientOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientOrganization");
                });

            modelBuilder.Entity("iE.Core.Reports.InspectionReport", b =>
                {
                    b.HasOne("iE.Core.Reports.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("iE.Core.Reports.ClientOrganization", null)
                        .WithMany("InspectionReports")
                        .HasForeignKey("ClientOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("iE.Core.Reports.Facility", null)
                        .WithMany("InspectionReports")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("iE.Core.Reports.ProcessUnit", null)
                        .WithMany()
                        .HasForeignKey("ProcessUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("iE.Core.Reports.InspectionFinding", "Findings", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<double?>("ApproximateFeetOfFindings")
                                .HasColumnType("double precision");

                            b1.Property<string>("AssociatedChecklistItem")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("ComponentType")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<double?>("CorrosionAllowance")
                                .HasColumnType("double precision");

                            b1.Property<int>("DamageMechanism")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.Property<string>("FindingType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("InspectionReportId")
                                .IsRequired()
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("InsulationCondition")
                                .HasColumnType("text");

                            b1.Property<bool>("IsGeneral")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsLocalized")
                                .HasColumnType("boolean");

                            b1.Property<string>("LineNumber")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<double?>("MinimumRequiredThickness")
                                .HasColumnType("double precision");

                            b1.Property<string>("NdeMethod")
                                .HasColumnType("text");

                            b1.Property<string>("NdeResult")
                                .HasColumnType("text");

                            b1.Property<List<string>>("PhotoIds")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<double?>("PitDepth")
                                .HasColumnType("double precision");

                            b1.Property<string>("RepairRecommendation")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.Property<bool>("RepairRequired")
                                .HasColumnType("boolean");

                            b1.Property<string>("Severity")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<double?>("ThicknessResult")
                                .HasColumnType("double precision");

                            b1.HasKey("Id");

                            b1.HasIndex("InspectionReportId");

                            b1.ToTable("InspectionFindings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InspectionReportId");
                        });

                    b.OwnsMany("iE.Core.Reports.InspectionObservation", "Observations", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("InspectionReportId")
                                .IsRequired()
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Notes")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.Property<List<string>>("PhotoIds")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.HasKey("Id");

                            b1.HasIndex("InspectionReportId");

                            b1.ToTable("InspectionObservations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InspectionReportId");
                        });

                    b.OwnsMany("iE.Core.Reports.InspectionPhoto", "Photos", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("FileName")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<string>("FileUrl")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("InspectionReportId")
                                .IsRequired()
                                .HasColumnType("character varying(64)");

                            b1.Property<bool>("PhotoAttached")
                                .HasColumnType("boolean");

                            b1.Property<string>("PhotoNumber")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<bool>("PhotoRequired")
                                .HasColumnType("boolean");

                            b1.Property<string>("RelatedChecklistItem")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("RelatedComponent")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("Id");

                            b1.HasIndex("InspectionReportId");

                            b1.ToTable("InspectionPhotos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InspectionReportId");
                        });

                    b.OwnsMany("iE.Core.Reports.InspectionReportSection", "Sections", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("InspectionReportId")
                                .IsRequired()
                                .HasColumnType("character varying(64)");

                            b1.Property<int?>("InstanceNumber")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsRepeatable")
                                .HasColumnType("boolean");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("SectionId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("SectionTitle")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("Id");

                            b1.HasIndex("InspectionReportId");

                            b1.ToTable("InspectionReportSections", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InspectionReportId");

                            b1.OwnsMany("iE.Core.Reports.InspectionReportAnswer", "Answers", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Comment")
                                        .HasMaxLength(4000)
                                        .HasColumnType("character varying(4000)");

                                    b2.Property<string>("DataType")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)");

                                    b2.Property<string>("FieldId")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)");

                                    b2.Property<string>("Label")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)");

                                    b2.Property<bool?>("PhotoRequired")
                                        .HasColumnType("boolean");

                                    b2.Property<bool?>("RecommendationRequired")
                                        .HasColumnType("boolean");

                                    b2.Property<int>("SectionId")
                                        .HasColumnType("integer");

                                    b2.Property<bool?>("TransferToComponentSection")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("Value")
                                        .HasMaxLength(4000)
                                        .HasColumnType("character varying(4000)");

                                    b2.Property<List<string>>("Values")
                                        .IsRequired()
                                        .HasColumnType("text[]");

                                    b2.HasKey("Id");

                                    b2.HasIndex("SectionId");

                                    b2.ToTable("InspectionReportAnswers", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SectionId");
                                });

                            b1.Navigation("Answers");
                        });


                    b.OwnsMany("iE.Core.Reports.ReportReviewHistory", "ReviewHistory", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("ReportId")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Comments")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.Property<DateTime>("PerformedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("PerformedByUserId")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.HasKey("Id");

                            b1.HasIndex("ReportId", "PerformedAt");

                            b1.ToTable("ReportReviewHistory", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.OwnsOne("iE.Core.Reports.PipingInspectionProfile", "PipingProfile", b1 =>
                        {
                            b1.Property<string>("InspectionReportId")
                                .HasColumnType("character varying(64)");

                            b1.Property<double?>("ApproximateFeetOfFindings")
                                .HasColumnType("double precision");

                            b1.Property<string>("DownstreamEquipment")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("FromLocation")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("InsulatedStatus")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("LineNumber")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<List<string>>("LineNumbers")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<string>("NominalPipeSize")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("PipingClass")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("ToLocation")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("UpstreamEquipment")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("InspectionReportId");

                            b1.ToTable("InspectionReports");

                            b1.WithOwner()
                                .HasForeignKey("InspectionReportId");
                        });

                    b.Navigation("Findings");

                    b.Navigation("Observations");

                    b.Navigation("Photos");

                    b.Navigation("PipingProfile");

                    b.Navigation("ReviewHistory");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("iE.Core.Reports.ProcessUnit", b =>
                {
                    b.HasOne("iE.Core.Reports.Facility", "Facility")
                        .WithMany("ProcessUnits")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("iE.Core.Reports.UserFacilityAccess", b =>
                {
                    b.HasOne("iE.Core.Reports.ClientOrganization", "ClientOrganization")
                        .WithMany("UserFacilityAccesses")
                        .HasForeignKey("ClientOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iE.Core.Reports.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClientOrganization");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("iE.Core.Reports.ClientOrganization", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("InspectionReports");

                    b.Navigation("UserFacilityAccesses");
                });

            modelBuilder.Entity("iE.Core.Reports.Facility", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("InspectionReports");

                    b.Navigation("ProcessUnits");
                });

            modelBuilder.Entity("iE.Core.Reports.ProcessUnit", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
