export type InspectionFieldDefinition = {
  fieldTag: string; label: string; standard: string; inspectionScope: string; equipmentFamily: string; equipmentSubtype: string; sectionGroup: string; componentType: string; dataType: string; options: string[]; required: boolean; defaultValue?: string | null; helpText?: string | null; supportsFinding: boolean; supportsRecommendation: boolean; supportsRepairRequired: boolean; supportsPhotoTag: boolean; supportsSummary: boolean; supportsNdeRequest: boolean; wordExportGroup: string; defaultLayoutOrder: number; reviewNotes?: string | null; futureOnly?: boolean;
};
export type InspectionFieldSet = { id: string; name: string; standard: string; inspectionScope: string; equipmentFamily: string; equipmentSubtype: string; componentPresets: string[]; fields: InspectionFieldDefinition[]; };

const f = (fieldTag:string,label:string,standard:string,inspectionScope:string,equipmentFamily:string,equipmentSubtype:string,sectionGroup:string,componentType:string,dataType:string,defaultLayoutOrder:number,extra:Partial<InspectionFieldDefinition>={}) : InspectionFieldDefinition => ({fieldTag,label,standard,inspectionScope,equipmentFamily,equipmentSubtype,sectionGroup,componentType,dataType,options:[],required:false,supportsFinding:false,supportsRecommendation:false,supportsRepairRequired:false,supportsPhotoTag:false,supportsSummary:false,supportsNdeRequest:false,wordExportGroup:`${standard}|${inspectionScope}|${equipmentFamily}|${equipmentSubtype}`,defaultLayoutOrder,...extra});

export const externalInspectionFieldSets: InspectionFieldSet[] = [
 {id:'api-570-external-piping',name:'API 570 External Piping',standard:'API 570',inspectionScope:'External',equipmentFamily:'Piping',equipmentSubtype:'General',componentPresets:[],fields:[f('component-type','Component Type','API 570','External','Piping','General','Component Section','Component','select',1,{options:['Valve','Other Component']}),f('component-tag-name','Component Tag/Name','API 570','External','Piping','General','Component Section','Component','text',2),f('location','Location','API 570','External','Piping','General','Component Section','Component','text',3),f('condition','Condition','API 570','External','Piping','General','Component Section','Component','select',4),f('finding-notes','Finding Notes','API 570','External','Piping','General','Findings','Component','textarea',5,{supportsFinding:true,supportsSummary:true}),f('recommendation-text','Recommendation Text','API 570','External','Piping','General','Recommendations','Component','textarea',6,{supportsRecommendation:true}),f('photo-reference-picture-tag','Photo Reference / Picture Tag','API 570','External','Piping','General','Photos','Component','text',7,{supportsPhotoTag:true}),f('create-finding','Create Finding','API 570','External','Piping','General','Findings','Component','boolean',8,{supportsFinding:true}),f('recommendation-required','Recommendation Required','API 570','External','Piping','General','Recommendations','Component','boolean',9,{supportsRecommendation:true}),f('repair-required','Repair Required','API 570','External','Piping','General','Repairs','Component','boolean',10,{supportsRepairRequired:true}),f('photo-required','Photo Required','API 570','External','Piping','General','Photos','Component','boolean',11,{supportsPhotoTag:true}),f('nde-required','NDE Required','API 570','External','Piping','General','NDE / Testing','Component','boolean',12,{supportsNdeRequest:true}),f('add-to-summary','Add to Summary','API 570','External','Piping','General','Return to Service','Component','boolean',13,{supportsSummary:true})]},
 {id:'api-510-external-exchangers',name:'API 510 External Exchangers',standard:'API 510',inspectionScope:'External',equipmentFamily:'Pressure Equipment',equipmentSubtype:'Exchanger',componentPresets:['Shell','Shell Cover','Channel Head','Channel Cover','Bonnet Head','Nozzles','Tubesheet Area','Flanges / Gaskets / Bolting','Saddles / Supports','Expansion Joint','Coating / Insulation Area','Platform / Ladder / Access','Nameplate / Markings','CML Locations','Other Component'],fields:[f('ext-cond','External Condition','API 510','External','Pressure Equipment','Exchanger','External Condition','Equipment','textarea',1)]},
 {id:'api-510-external-drum-vessel',name:'API 510 External Drums / Pressure Vessels',standard:'API 510',inspectionScope:'External',equipmentFamily:'Pressure Equipment',equipmentSubtype:'Drum / Vessel',componentPresets:['Shell','Heads','Nozzles','Manways','Flanges / Gaskets / Bolting','Saddle / Skirt / Legs','Supports / Foundation','Platforms / Ladders / Handrails','Coating','Insulation','Nameplate / Markings','CML Locations','Other Component'],fields:[f('drum-cond','External Condition','API 510','External','Pressure Equipment','Drum / Vessel','External Condition','Equipment','textarea',1)]},
 {id:'api-510-external-tower-column',name:'API 510 External Towers / Columns',standard:'API 510',inspectionScope:'External',equipmentFamily:'Pressure Equipment',equipmentSubtype:'Tower / Column',componentPresets:['Shell Courses','Heads','Nozzles','Manways','Skirt','Base Ring / Anchor Bolts','Platforms / Ladders / Handrails','Insulation / Jacketing','Coating','Nameplate / Markings','CML Locations','Other Component'],fields:[f('tower-cond','External Condition','API 510','External','Pressure Equipment','Tower / Column','External Condition','Equipment','textarea',1)]},
];

export const futureOnlyApi510InternalFields: InspectionFieldDefinition[] = [f('future-only-internal','API 510 Internal Placeholder','API 510','Internal','Pressure Equipment','Vessel','Internal Inspection','Internal','textarea',1,{futureOnly:true,reviewNotes:'Future-only internal inspection field. Excluded from MVP export.'})];

export const getMvpExternalInspectionFields = () => externalInspectionFieldSets.flatMap((s) => s.fields);
