using iE.Api.Auth;
using iE.Api.Tenancy;
using iE.Core.Reports;
using iE.Core.Reports.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace iE.Tests;

public class TenantMemberServiceTests
{
    [Fact] public async Task Invite_Normalizes_Email() { var svc = Build(false, false, out var db, out _); var r = await svc.InviteMemberAsync("  User@Example.com  ", "t1"); Assert.True(r.Allowed); Assert.Equal(ClientOrganizationUserStatuses.Invited, Assert.Single(db.ClientOrganizationUsers).Status); Assert.Equal("user@example.com", Assert.Single(db.ClientOrganizationUsers).NormalizedEmail); }
    [Fact] public async Task Duplicate_Email_SameTenant_ActiveOrInvited_Denied() { var svc = Build(false, false, out var db, out _); db.ClientOrganizationUsers.Add(User("u1","t1",ClientOrganizationUserStatuses.Active,email:"a@b.com")); await db.SaveChangesAsync(); var r = await svc.InviteMemberAsync("a@b.com","t1"); Assert.False(r.Allowed); Assert.Equal("duplicate_member",r.ReasonCode); }
    [Fact] public async Task Duplicate_Email_DifferentTenant_Allowed() { var svc = Build(false, false, out var db, out _); db.ClientOrganizationUsers.Add(User("u1","t2",ClientOrganizationUserStatuses.Active,email:"a@b.com")); await db.SaveChangesAsync(); var r = await svc.InviteMemberAsync("a@b.com","t1"); Assert.True(r.Allowed); }
    [Fact] public async Task Duplicate_ExternalSubject_SameTenant_Active_Denied() { var svc = Build(false, false, out var db, out _); var invite=await svc.InviteMemberAsync("x@y.com","t1"); db.ClientOrganizationUsers.Add(User("u2","t1",ClientOrganizationUserStatuses.Active,subject:"sub-1")); await db.SaveChangesAsync(); var r = await svc.ActivateMemberAsync(invite.MemberId!,"sub-1","t1"); Assert.False(r.Allowed); Assert.Equal("duplicate_member",r.ReasonCode); }
    [Fact] public async Task Reinvite_DisabledMember_Reinvites_After_SeatCheck() { var svc = Build(true, false, out var db, out _, limit:2); db.ClientOrganizationUsers.Add(User("u1","t1",ClientOrganizationUserStatuses.Disabled,email:"a@b.com")); await db.SaveChangesAsync(); var r = await svc.InviteMemberAsync("a@b.com","t1"); Assert.True(r.Allowed); Assert.Equal(ClientOrganizationUserStatuses.Invited, (await db.ClientOrganizationUsers.FirstAsync()).Status); }
    [Fact] public async Task Activate_DisabledMember_Checks_SeatLimit() { var svc = Build(true, false, out var db, out var audit, limit:1); db.ClientOrganizationUsers.AddRange(User("u1","t1",ClientOrganizationUserStatuses.Active,subject:"active"),User("u2","t1",ClientOrganizationUserStatuses.Disabled,email:"b@c.com")); await db.SaveChangesAsync(); var r = await svc.ActivateMemberAsync("u2","sub-2","t1"); Assert.False(r.Allowed); Assert.Equal("seat_limit_exceeded",r.ReasonCode); Assert.Contains(audit.Events,e=>e.Action==AuditActions.TenantMemberSeatLimitDenied); }
    [Fact] public async Task Invite_EnforcementDisabled_Allows_OverLimit() { var svc = Build(false, false, out var db, out _, limit:1); db.ClientOrganizationUsers.AddRange(User("u1","t1",ClientOrganizationUserStatuses.Active),User("u2","t1",ClientOrganizationUserStatuses.Invited)); await db.SaveChangesAsync(); Assert.True((await svc.InviteMemberAsync("x@y.com","t1")).Allowed); }
    [Fact] public async Task Invite_EnforcementEnabled_BelowLimit_Allows() { var svc = Build(true, false, out var db, out _, limit:2); db.ClientOrganizationUsers.Add(User("u1","t1",ClientOrganizationUserStatuses.Active)); await db.SaveChangesAsync(); Assert.True((await svc.InviteMemberAsync("x@y.com","t1")).Allowed); }
    [Fact] public async Task Invite_EnforcementEnabled_AtLimit_Denies() { var svc = Build(true, false, out var db, out _, limit:1); db.ClientOrganizationUsers.Add(User("u1","t1",ClientOrganizationUserStatuses.Active)); await db.SaveChangesAsync(); Assert.False((await svc.InviteMemberAsync("x@y.com","t1")).Allowed); }
    [Fact] public async Task Null_MaxUsers_Allows_Unlimited() { var svc = Build(true, false, out var db, out _, limit:null); db.ClientOrganizationUsers.AddRange(User("u1","t1",ClientOrganizationUserStatuses.Active),User("u2","t1",ClientOrganizationUserStatuses.Invited)); await db.SaveChangesAsync(); Assert.True((await svc.InviteMemberAsync("x@y.com","t1")).Allowed); }
    [Fact] public async Task Missing_Entitlement_Denies_When_Enabled() { var svc = Build(true, false, out _, out _, includeEntitlement:false); var r = await svc.InviteMemberAsync("x@y.com","t1"); Assert.False(r.Allowed); Assert.Equal("entitlement_disabled",r.ReasonCode); }
    [Fact] public async Task AuthEnabled_MissingTenant_Denies() { var svc = Build(false, true, out _, out _, setTenant:false); var r = await svc.InviteMemberAsync("x@y.com"); Assert.False(r.Allowed); Assert.Equal("tenant_context_missing", r.ReasonCode); }
    [Fact] public async Task AuthEnabled_ExplicitOtherTenant_Ignored() { var svc = Build(false, true, out var db, out _, tenantId:"11111111-1111-1111-1111-111111111111"); var r = await svc.InviteMemberAsync("x@y.com","22222222-2222-2222-2222-222222222222"); Assert.True(r.Allowed); Assert.Equal("11111111-1111-1111-1111-111111111111", Assert.Single(db.ClientOrganizationUsers).ClientOrganizationId); }
    [Fact] public async Task SeatUsage_Rules_ActiveInvited_Consume_DisabledRemoved_No() { var db = Db(); db.ClientOrganizationUsers.AddRange(User("u1","t1",ClientOrganizationUserStatuses.Active),User("u2","t1",ClientOrganizationUserStatuses.Invited),User("u3","t1",ClientOrganizationUserStatuses.Disabled),User("u4","t1",ClientOrganizationUserStatuses.Removed)); await db.SaveChangesAsync(); var usage = await new SubscriptionSeatUsageService(Cfg(false,false), new TenantContextAccessor(), db).GetUsageAsync("t1"); Assert.Equal(2, usage!.ConsumedSeatCount); }
    [Fact] public async Task Audit_Metadata_AllowList_Only() { var svc = Build(false, false, out _, out var audit); var invite = await svc.InviteMemberAsync("x@y.com","t1"); await svc.ActivateMemberAsync(invite.MemberId!,"sub-1","t1"); await svc.DisableMemberAsync(invite.MemberId!,"t1"); await svc.RemoveMemberAsync(invite.MemberId!,"t1"); var allowed = new HashSet<string>{"operation","reasonCode","targetUserId","hasEmail","hasExternalSubject","consumedSeatCount","limitValue"}; foreach(var evt in audit.Events){ if(evt.Metadata is null) continue; Assert.All(evt.Metadata.Keys,k=>Assert.Contains(k,allowed)); Assert.DoesNotContain("requestBody",evt.Metadata.Keys); Assert.DoesNotContain("token",evt.Metadata.Keys); Assert.DoesNotContain("metadataJson",evt.Metadata.Keys, StringComparer.OrdinalIgnoreCase);} }

    static TenantMemberService Build(bool enforcementEnabled, bool authEnabled, out InspectionReportsDbContext db, out CapturingAuditWriter audit, int? limit = 2, bool includeEntitlement = true, bool setTenant = true, string tenantId = "t1")
    {
        db = Db(); SeedSubscription(db, "t1", limit, includeEntitlement); SeedSubscription(db, "11111111-1111-1111-1111-111111111111", limit, includeEntitlement);
        var cfg = Cfg(enforcementEnabled, authEnabled);
        var tenant = new TenantContextAccessor(); if (authEnabled && setTenant) tenant.Current = new TenantContext { ClientOrganizationId = Guid.Parse(tenantId) };
        var guard = new EntitlementSeatLimitGuard(cfg, new EntitlementGuard(cfg, new EntitlementService(cfg, tenant, db)), new SubscriptionSeatUsageService(cfg, tenant, db));
        audit = new CapturingAuditWriter();
        return new TenantMemberService(cfg, tenant, db, guard, audit);
    }

    static IConfiguration Cfg(bool enforcementEnabled, bool authEnabled) => new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string, string?> { ["Subscriptions:EnforcementEnabled"] = enforcementEnabled.ToString().ToLowerInvariant(), ["Authentication:Enabled"] = authEnabled.ToString().ToLowerInvariant() }).Build();
    static InspectionReportsDbContext Db() => new(new DbContextOptionsBuilder<InspectionReportsDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);
    static void SeedSubscription(InspectionReportsDbContext db, string tenantId, int? limit, bool includeEntitlement) { var planId=$"p-{tenantId}"; db.SubscriptionPlans.Add(new SubscriptionPlan { Id = planId, Name = "Plan", PlanCode = planId }); db.ClientSubscriptions.Add(new ClientSubscription { Id = $"s-{tenantId}", ClientOrganizationId = tenantId, PlanId = planId, Status = SubscriptionStatuses.Active, StartsAtUtc = DateTime.UtcNow.AddDays(-1) }); if (includeEntitlement) db.SubscriptionEntitlements.Add(new SubscriptionEntitlement { Id = $"e-{tenantId}", PlanId = planId, EntitlementKey = EntitlementKeys.MaxUsers, Enabled = true, LimitValue = limit }); db.SaveChanges(); }
    static ClientOrganizationUser User(string id, string tenantId, string status, string? email = null, string? subject = null) => new() { Id = id, ClientOrganizationId = tenantId, Status = status, Email = email, NormalizedEmail = email?.Trim().ToLowerInvariant(), ExternalSubject = subject ?? $"subject-{id}", CreatedAtUtc = DateTime.UtcNow };

    sealed class CapturingAuditWriter : IAuditEventWriter { public List<(string Action, IDictionary<string, object?>? Metadata)> Events { get; } = []; public Task WriteAsync(string action, string resourceType, string? resourceId, string result, string? facilityId = null, IDictionary<string, object?>? metadata = null, CancellationToken cancellationToken = default) { Events.Add((action, metadata)); return Task.CompletedTask; } }
}
