using iE.Api.Tenancy;
using iE.Core.Reports.Domain;
using iE.Core.Reports.Persistence;
using Microsoft.EntityFrameworkCore;

namespace iE.Api.Workflow;

public sealed record WorkflowQueryFilter(string? TenantId=null, string? FacilityId=null, string? AssetId=null, string? ReportId=null, string? Status=null, DateTime? FromUtc=null, DateTime? ToUtc=null, bool? IncludeCancelled=null, int Skip=0, int Take=50);
public sealed record NdeRequestQueryFilter(string? TenantId=null, string? FacilityId=null, string? AssetId=null, string? ReportId=null, string? Status=null, string? Priority=null, string? NdeType=null, DateTime? FromUtc=null, DateTime? ToUtc=null, bool? DueSoon=null, bool? Overdue=null, bool? IncludeCancelled=null, bool? ResultsReceived=null, int Skip=0, int Take=50);
public sealed record ReportLibraryQueryFilter(string? TenantId=null, string? FacilityId=null, string? AssetId=null, string? ReportId=null, string? Status=null, string? ReportType=null, DateTime? FromUtc=null, DateTime? ToUtc=null, int Skip=0, int Take=50);
public sealed record QueryEnvelope<T>(string ReasonCode, IReadOnlyList<T> Items);
public sealed record NdeRequestSummary(string Id,string? RequestNumber,string? ClientOrganizationId,string FacilityId,string? ProcessUnitId,string? AssetId,string? ReportId,string NdeType,string NdeTypeDisplayName,string Priority,string Status,string DisplayStatus,string ReasonSummary,string? RequestedByUserId,string? RequestedByExternalSubject,string? AssignedToName,string? VendorName,DateTime? DueDateUtc,DateTime? ScheduledAtUtc,DateTime? ResultsReceivedAtUtc,DateTime? ClosedAtUtc,DateTime? CanceledAtUtc,DateTime LastActivityAtUtc,bool HasResults,bool IsCancelled,bool IsOverdue,bool IsDueSoon,bool CanDownloadReport,bool CanBulkExport);
public sealed record OwnerApprovalQueueItem(string NdeRequestId,string FacilityId,string Priority,string Status,bool IsOverdue,bool HasResultsReceived,bool IsCancelled,DateTime LastActivityAtUtc);
public sealed record ClientNdeRequestLogItem(string Id,string? RequestNumber,string FacilityId,string? ProcessUnitId,string? AssetId,string? ReportId,string NdeType,string Priority,string Status,string DisplayStatus,DateTime LastActivityAtUtc,bool HasResults,bool IsCancelled);
public sealed record ReportLibraryItem(string ReportId,string ReportNumber,string ReportType,string TemplateId,string FacilityId,string? ProcessUnitId,string? AssetId,string EquipmentTag,string Status,string DisplayStatus,DateTime CreatedAt,DateTime? UpdatedAt,DateTime? FinalizedAt,DateTime LastActivityAtUtc,bool HasNdeRequests,bool HasReportLogEntries,bool CanDownload,bool CanBulkExport,bool IsApiInspection,bool IsNdeReport);
public sealed record ReportTimelineItem(string Id,string ReportId,string EventType,string DisplayLabel,string? EventStatus,string? FromStatus,string? ToStatus,string? RelatedNdeRequestId,DateTime CreatedAtUtc,string? ActorDisplayName,string Message);
public sealed record AssetActivityItem(string Kind,string Id,string Status,DateTime CreatedAtUtc);
public sealed record AssetActivitySummary(string AssetId,int ActiveReports,int FinalReports,int OpenNdeRequests,int ClosedOrCancelledNdeRequests,int ResultsReceivedCount,IReadOnlyList<AssetActivityItem> RecentTimelineEvents);

public interface IWorkflowReadModelService {
Task<QueryEnvelope<NdeRequestSummary>> QueryNdeRequestsAsync(NdeRequestQueryFilter filter, CancellationToken ct=default);
Task<QueryEnvelope<OwnerApprovalQueueItem>> QueryOwnerApprovalQueueAsync(WorkflowQueryFilter filter, CancellationToken ct=default);
Task<QueryEnvelope<ClientNdeRequestLogItem>> QueryClientNdeLogAsync(NdeRequestQueryFilter filter, CancellationToken ct=default);
Task<QueryEnvelope<ReportLibraryItem>> QueryReportLibraryAsync(ReportLibraryQueryFilter filter, bool clientView=false, CancellationToken ct=default);
Task<QueryEnvelope<ReportTimelineItem>> QueryReportTimelineAsync(WorkflowQueryFilter filter, CancellationToken ct=default);
Task<(string ReasonCode, AssetActivitySummary? Item)> QueryAssetActivityAsync(WorkflowQueryFilter filter, CancellationToken ct=default);
}

public sealed class WorkflowReadModelService(InspectionReportsDbContext db, ITenantContextAccessor tenantAccessor, IConfiguration config) : IWorkflowReadModelService {
const int MaxTake = 200;
(bool ok,string? tenant) ResolveTenant(string? requested){var enabled=config.GetValue<bool>("Authentication:Enabled"); if(enabled){ var current=tenantAccessor.Current.ClientOrganizationId?.ToString(); return string.IsNullOrWhiteSpace(current)?(false,null):(true,current);} return string.IsNullOrWhiteSpace(requested)?(false,null):(true,requested);}    
int SafeTake(int take)=>Math.Clamp(take<=0?50:take,1,MaxTake);
public async Task<QueryEnvelope<NdeRequestSummary>> QueryNdeRequestsAsync(NdeRequestQueryFilter filter, CancellationToken ct=default){var (ok,tenant)=ResolveTenant(filter.TenantId); if(!ok) return new("tenant_context_missing",[]); var now=DateTime.UtcNow; var q=db.NdeRequests.AsNoTracking().Where(x=>x.ClientOrganizationId==tenant); if(filter.FacilityId is not null) q=q.Where(x=>x.FacilityId==filter.FacilityId); if(filter.AssetId is not null) q=q.Where(x=>x.AssetId==filter.AssetId); if(filter.ReportId is not null) q=q.Where(x=>x.ReportId==filter.ReportId); if(filter.Status is not null) q=q.Where(x=>x.Status==filter.Status); if(filter.Priority is not null) q=q.Where(x=>x.Priority==filter.Priority); if(filter.NdeType is not null) q=q.Where(x=>x.NdeType==filter.NdeType); if(filter.IncludeCancelled==false) q=q.Where(x=>x.Status!=NdeRequestStatuses.Canceled); var rows=await q.OrderByDescending(x=>x.UpdatedAtUtc??x.CreatedAtUtc).Skip(Math.Max(0,filter.Skip)).Take(SafeTake(filter.Take)).ToListAsync(ct); var items=rows.Select(x=>{var last=x.UpdatedAtUtc??x.CreatedAtUtc;var overdue=x.DueDateUtc is DateTime d && d<now && x.Status!=NdeRequestStatuses.Closed && x.Status!=NdeRequestStatuses.Canceled;var soon=x.DueDateUtc is DateTime due && due>=now && due<=now.AddDays(7);return new NdeRequestSummary(x.Id,x.RequestNumber,x.ClientOrganizationId,x.FacilityId,x.ProcessUnitId,x.AssetId,x.ReportId,x.NdeType,x.NdeType,x.Priority,x.Status,x.Status,x.Reason,x.RequestedByUserId,x.RequestedByExternalSubject,x.AssignedToName,x.VendorName,x.DueDateUtc,x.ScheduledAtUtc,x.ResultsReceivedAtUtc,x.ClosedAtUtc,x.CanceledAtUtc,last,x.ResultsReceivedAtUtc is not null,x.Status==NdeRequestStatuses.Canceled,overdue,soon,false,false);}).ToList(); return new("allowed",items);}    
public async Task<QueryEnvelope<OwnerApprovalQueueItem>> QueryOwnerApprovalQueueAsync(WorkflowQueryFilter filter, CancellationToken ct=default){var baseRes=await QueryNdeRequestsAsync(new NdeRequestQueryFilter(filter.TenantId,filter.FacilityId,filter.AssetId,filter.ReportId,filter.Status,null,null,filter.FromUtc,filter.ToUtc,null,null,filter.IncludeCancelled,null,filter.Skip,filter.Take),ct); var items=baseRes.Items.Where(x=>x.Priority is "high" or "urgent" || x.IsOverdue || x.HasResults || x.IsCancelled || x.Status==NdeRequestStatuses.Requested).Select(x=>new OwnerApprovalQueueItem(x.Id,x.FacilityId,x.Priority,x.Status,x.IsOverdue,x.HasResults,x.IsCancelled,x.LastActivityAtUtc)).ToList(); return new(baseRes.ReasonCode,items);}    
public async Task<QueryEnvelope<ClientNdeRequestLogItem>> QueryClientNdeLogAsync(NdeRequestQueryFilter filter, CancellationToken ct=default){var res=await QueryNdeRequestsAsync(filter,ct); var items=res.Items.Where(x=>x.ReportId is null || x.CanDownloadReport || x.Status==NdeRequestStatuses.Closed || x.Status==NdeRequestStatuses.ResultsReceived).Select(x=>new ClientNdeRequestLogItem(x.Id,x.RequestNumber,x.FacilityId,x.ProcessUnitId,x.AssetId,x.ReportId,x.NdeType,x.Priority,x.Status,x.DisplayStatus,x.LastActivityAtUtc,x.HasResults,x.IsCancelled)).ToList(); return new(res.ReasonCode,items);}    
public async Task<QueryEnvelope<ReportLibraryItem>> QueryReportLibraryAsync(ReportLibraryQueryFilter filter, bool clientView=false, CancellationToken ct=default){var (ok,tenant)=ResolveTenant(filter.TenantId); if(!ok) return new("tenant_context_missing",[]); var reports=db.InspectionReports.AsNoTracking().Where(x=>x.ClientOrganizationId==tenant); if(filter.FacilityId is not null) reports=reports.Where(x=>x.FacilityId==filter.FacilityId); if(filter.AssetId is not null) reports=reports.Where(x=>x.AssetId==filter.AssetId); if(filter.ReportId is not null) reports=reports.Where(x=>x.Id==filter.ReportId); if(filter.Status is not null) reports=reports.Where(x=>x.Status==filter.Status); if(clientView) reports=reports.Where(x=>x.Status==InspectionReportStatuses.Final); var rows=await reports.OrderByDescending(x=>x.UpdatedAt??x.CreatedAt).Skip(Math.Max(0,filter.Skip)).Take(SafeTake(filter.Take)).ToListAsync(ct); var ids=rows.Select(x=>x.Id).ToList(); var ndeBy=await db.NdeRequests.AsNoTracking().Where(x=>x.ClientOrganizationId==tenant && x.ReportId!=null && ids.Contains(x.ReportId)).GroupBy(x=>x.ReportId!).Select(g=>new{g.Key,C=g.Count()}).ToDictionaryAsync(x=>x.Key,x=>x.C,ct); var logBy=await db.ReportLogEntries.AsNoTracking().Where(x=>x.ClientOrganizationId==tenant && ids.Contains(x.ReportId)).GroupBy(x=>x.ReportId).Select(g=>new{g.Key,C=g.Count(),Last=g.Max(z=>z.CreatedAtUtc)}).ToDictionaryAsync(x=>x.Key,x=>(x.C,x.Last),ct); var items=rows.Select(r=>new ReportLibraryItem(r.Id,r.ReportNumber,r.TemplateId,r.TemplateId,r.FacilityId,r.ProcessUnitId,r.AssetId,r.EquipmentTag,r.Status,r.Status,r.CreatedAt,r.UpdatedAt,r.Status==InspectionReportStatuses.Final?(r.UpdatedAt??r.CreatedAt):null,logBy.TryGetValue(r.Id,out var l)?l.Last:(r.UpdatedAt??r.CreatedAt),ndeBy.ContainsKey(r.Id),logBy.ContainsKey(r.Id),r.Status==InspectionReportStatuses.Final,r.Status==InspectionReportStatuses.Final,r.TemplateId.Contains("api",StringComparison.OrdinalIgnoreCase),false)).ToList(); return new("allowed",items);}    
public async Task<QueryEnvelope<ReportTimelineItem>> QueryReportTimelineAsync(WorkflowQueryFilter filter, CancellationToken ct=default){var (ok,tenant)=ResolveTenant(filter.TenantId); if(!ok) return new("tenant_context_missing",[]); if(string.IsNullOrWhiteSpace(filter.ReportId)) return new("invalid_filter",[]); var q=db.ReportLogEntries.AsNoTracking().Where(x=>x.ClientOrganizationId==tenant && x.ReportId==filter.ReportId); if(filter.FacilityId is not null) q=q.Where(x=>x.FacilityId==filter.FacilityId); var rows=await q.OrderBy(x=>x.CreatedAtUtc).Skip(Math.Max(0,filter.Skip)).Take(SafeTake(filter.Take)).ToListAsync(ct); return new("allowed",rows.Select(x=>new ReportTimelineItem(x.Id,x.ReportId,x.EventType,x.EventType,x.EventStatus,x.FromStatus,x.ToStatus,x.RelatedNdeRequestId,x.CreatedAtUtc,null,x.Message)).ToList());}
public async Task<(string ReasonCode, AssetActivitySummary? Item)> QueryAssetActivityAsync(WorkflowQueryFilter filter, CancellationToken ct=default){var (ok,tenant)=ResolveTenant(filter.TenantId); if(!ok) return ("tenant_context_missing",null); if(string.IsNullOrWhiteSpace(filter.AssetId)) return ("invalid_filter",null); var reports=await db.InspectionReports.AsNoTracking().Where(x=>x.ClientOrganizationId==tenant&&x.AssetId==filter.AssetId&&(filter.FacilityId==null||x.FacilityId==filter.FacilityId)).ToListAsync(ct); var ndes=await db.NdeRequests.AsNoTracking().Where(x=>x.ClientOrganizationId==tenant&&x.AssetId==filter.AssetId&&(filter.FacilityId==null||x.FacilityId==filter.FacilityId)).ToListAsync(ct); var reportIds=reports.Select(x=>x.Id).ToList(); var timeline=await db.ReportLogEntries.AsNoTracking().Where(x=>x.ClientOrganizationId==tenant&&reportIds.Contains(x.ReportId)).OrderByDescending(x=>x.CreatedAtUtc).Take(20).ToListAsync(ct); return ("allowed",new AssetActivitySummary(filter.AssetId!,reports.Count(x=>x.Status!=InspectionReportStatuses.Final),reports.Count(x=>x.Status==InspectionReportStatuses.Final),ndes.Count(x=>x.Status!=NdeRequestStatuses.Closed&&x.Status!=NdeRequestStatuses.Canceled),ndes.Count(x=>x.Status==NdeRequestStatuses.Closed||x.Status==NdeRequestStatuses.Canceled),ndes.Count(x=>x.ResultsReceivedAtUtc!=null),timeline.Select(x=>new AssetActivityItem(x.EventType,x.Id,x.EventStatus??string.Empty,x.CreatedAtUtc)).ToList()));}
}
